NAME=ls
LANG = c++
.include	<../Makefile>
LDFLAGS += -lboost_filesystem
CFLAGS += -pthread -isystem /usr/local/include/boost/ -isystem /usr/local/include

#compiling options
.PHONY:	build clean

$(NAME): 

clean: nameclean objclean coreclean
