NAME=cp
LANG = c++
.include	<../Makefile>
LDFLAGS += -lboost_filesystem
CFLAGS += -pthread -isystem /usr/local/include/boost/

#compiling options
.PHONY:	clean

$(NAME): 

clean: nameclean coreclean objclean
