#!/usr/bin/env sh
base="$(basename $0)";
optdir="/home/eitan/.vlc_extra";
current_sock="$(cat $optdir/socket_name)";
if [ -e "$current_sock" ]
then
	Xdialog --icon ~/bin/icons/warning.xpm --infobox "VLC already running...." 0 0 2000;
	return 1;
fi
TMPFILE=$(mktemp $optdir/sockets/XXXXXX);
#we can't operate if the file exists....
rm "$TMPFILE";
echo $TMPFILE;
echo "$TMPFILE">$optdir/socket_name;
# -L == loop; -d == deamon;
vlc --intf rc --rc-unix "$TMPFILE" --rc-fake-tty -L --no-media-library -d --volume 1024; 
