#!/usr/bin/env sh

install_me()
{
	whomedir="$1";
	mkdir "$whomedir";
	touch "$whomedir/socket_name";
	mkdir "$whomedir/sockets";
}

cleanup="";
ncurse="";
optdir=~/.vlc_extra;
while getopts co:n opt
do
	case "$opt" in
		'c') cleanup="YES";;
		'n') ncurse="YES";;
		'o') optdir="$OPTARG";;
		'?') exit 1;;
	esac
done
# if we don't exist lettuce install ourself
if [ ! -d "$optdir" ]
then
	install_me "$optdir";
fi

[ -n "$cleanup" ] && echo "Yeah!";
base="$(basename $0)";
current_sock="$(cat $optdir/socket_name)";
if [ -n "$cleanup" ]
then
	# exit program if currently running
	vlc.do -c quit;
	# remove the socket file (not deleted before if program not running)
	rm $current_sock;
	# empty the current socket file...
	:>$optdir/socket_name;
fi

if [ -e "$current_sock" ]
then
	Xdialog --icon ~/bin/icons/warning.xpm --infobox "VLC already running...." 0 0 2000;
	return 1;
fi
TMPFILE=$(mktemp $optdir/sockets/XXXXXX);
#we can't operate if the file exists....
rm "$TMPFILE";
echo $TMPFILE;
echo "$TMPFILE">$optdir/socket_name;
# -L == loop; -d == deamon;
vlc_opts="--rc-unix "$TMPFILE" --rc-fake-tty -L --no-media-library -d --volume 1024";
if [ -n "$ncurse" ]
then
	vlc --intf rc --extraintf ncurses $vlc_opts;
else
	vlc --intf rc $vlc_opts;
fi
return 0;