NAME=icebreaker
LANG = c++
.include    <../Makefile>

#compiling options
.PHONY:     clean

all:  $(NAME) terrain.o

$(NAME): terrain.cpp

terrain.o: 

clean:
	rm -fv *.o
	rm -f ./$(NAME) ./$(NAME).core

