.\" Man page for symports
.\"
.\" Copyright (c) 2009, Eitan Adler EitanAdlerList@gmail.com
.\" Supplementary style provided by Thomas Abthorpe, tabthorpe@FreeBSD.org
.\"
.Dd June 7, 2009
.Dt SYMPORTS 1
.Os
.Sh NAME
.Nm symports
.Nd generates symlinks for virtual ports
.Sh SYNOPSIS
.Nm
.Op -dnv
.Op  -iindexFile 
.Op -pPortdir
.Op -wWhereT
.Sh DESCRIPTION
.Nm
reads through your ports tree and generates
a tree using symlinks for all categories - not just the "real"
ones.
.Sh OPTIONS
.TP
.B \-p \fI Ports directory \fP
The location of the ports directory you want to work with.
.TP
.B \-i \fI Index file location \fP
Uses the index file instead of each port\'s Makefile
.TP
.B \-w \fI Archive directory \fP 
Where should the symlinks be generated.
Defaults to current working directory.
.TP
.B \-n
Display the commands that would have been executed, but do not actually execute them.
.TP
.B \-v
Be verbose.
.TP
.B \-?
Displays help.
.TP
.B \-d
Displays debugging info.
.Sh NOTES
.Nm
has been tested on a system with imcomplete ports,
but has not been tested under all known conditions.
.Sh BUGS
Please send any bug reports to EitanAdlerList@gmail.com
.Sh SEE ALSO
.Xr ports 7
.Sh AUTHOR
Eitan Adler <EitanAdlerList@gmail.com> wrote
.Nm
as well as its accompanying man page. Contributions always welcome.