.\" Man page for symports
.\"
.\" Copyright (c) 2009, Eitan Adler EitanAdlerList@gmail.com
.\" Supplementary style provided by Thomas Abthorpe, tabthorpe@FreeBSD.org
.\"
.Dd June 7, 2009
.Dt SYMPORTS 1
.Os
.Sh NAME
.Nm symports
.Nd generates symlinks for virtual ports
.Sh SYNOPSIS
.Nm
.Op -dnv
.Op -i indexFile 
.Op -p Portsdir
.Op -w WhereT
.Sh DESCRIPTION
.Nm
reads through your ports tree and generates
a tree using symlinks for all categories - not just the "real"
ones.
.Sh OPTIONS
.Bl -tag -width "Fl p"
.It Fl p Ar directory
The location of the ports directory you want to work with.
.It Fl i Ar INDEX file location
Uses the index file instead of each port\'s Makefile
.It Fl w Ar Archive directory
Where the symlinks should be generated.
Defaults to current working directory.
.It Fl n
Display the commands that would have been executed, but do not actually execute them.
.It Fl v
Be verbose.
.It Fl ?
Displays help.
.It Fl d
Displays debugging info.
.El
.Sh NOTES
.Nm
has been tested on a system with incomplete ports,
but has not been tested under all known conditions.
.Sh BUGS
Please send any bug reports to EitanAdlerList@gmail.com
.Sh SEE ALSO
.Xr ports 7
.Sh AUTHOR
Eitan Adler <EitanAdlerList@gmail.com> wrote
.Nm
as well as its accompanying man page. Contributions always welcome.
